import type { ProjectRoadmap } from '@/types/idea';

export function roadmapToMarkdown(roadmap: ProjectRoadmap): string {
  const lines: string[] = [];

  lines.push(`# ${roadmap.title}`);
  lines.push(`> ${roadmap.tagline}`);
  lines.push('');

  // Stats
  lines.push(`**Difficulty:** ${roadmap.difficulty_score}/10 | **Est. Hours:** ${roadmap.estimated_total_hours}h | **Features:** ${roadmap.core_features.length} | **Weeks:** ${roadmap.roadmap.length}`);
  lines.push('');

  // First thing to build
  lines.push('## First Thing to Build');
  lines.push(roadmap.first_thing_to_build);
  lines.push('');

  // Problem + Target
  lines.push('## Problem Statement');
  lines.push(roadmap.problem_statement);
  lines.push('');
  lines.push(`**Target User:** ${roadmap.target_user}`);
  lines.push('');

  // Unique angle
  lines.push('## Unique Angle');
  lines.push(roadmap.unique_angle);
  lines.push('');

  // Tech Stack
  lines.push('## Tech Stack');
  lines.push(`- **Frontend:** ${roadmap.tech_stack.frontend}`);
  lines.push(`- **Backend:** ${roadmap.tech_stack.backend}`);
  lines.push(`- **Database:** ${roadmap.tech_stack.database}`);
  lines.push(`- **Auth:** ${roadmap.tech_stack.auth}`);
  lines.push(`- **Hosting:** ${roadmap.tech_stack.hosting}`);
  if (roadmap.tech_stack.extras.length > 0) {
    lines.push(`- **Extras:** ${roadmap.tech_stack.extras.join(', ')}`);
  }
  lines.push('');

  // Core Features
  lines.push('## Core Features');
  for (const f of roadmap.core_features) {
    const priorityTag = f.priority === 'must' ? '🔴' : f.priority === 'should' ? '🟡' : '🟢';
    lines.push(`- ${priorityTag} **${f.name}** (${f.est_hours}h) — ${f.description}`);
  }
  lines.push('');

  // Weekly Roadmap
  lines.push('## Weekly Roadmap');
  for (const w of roadmap.roadmap) {
    lines.push(`### Week ${w.week}: ${w.milestone}`);
    for (const t of w.tasks) {
      lines.push(`- [ ] ${t}`);
    }
    lines.push(`**Deliverable:** ${w.deliverable}`);
    lines.push('');
  }

  // Technical Risks
  if (roadmap.technical_risks.length > 0) {
    lines.push('## Technical Risks');
    for (const r of roadmap.technical_risks) {
      lines.push(`- ⚠️ ${r}`);
    }
    lines.push('');
  }

  // Similar Products
  if (roadmap.similar_products.length > 0) {
    lines.push('## Similar Products');
    lines.push(roadmap.similar_products.join(', '));
    lines.push('');
  }

  // Competitive Analysis
  if (roadmap.competitive_analysis) {
    lines.push('## Competitive Analysis');
    for (const c of roadmap.competitive_analysis.competitors) {
      lines.push(`### ${c.name}`);
      lines.push(c.description);
      lines.push('**Strengths:**');
      for (const s of c.strengths) lines.push(`- ${s}`);
      lines.push('**Weaknesses:**');
      for (const w of c.weaknesses) lines.push(`- ${w}`);
      lines.push(`**How We Differ:** ${c.how_we_differ}`);
      lines.push('');
    }
    lines.push(`**Market Gap:** ${roadmap.competitive_analysis.market_gap}`);
    lines.push(`**Positioning Strategy:** ${roadmap.competitive_analysis.positioning_strategy}`);
    lines.push('');
  }

  // Tech Recommendations
  if (roadmap.tech_recommendations && roadmap.tech_recommendations.length > 0) {
    lines.push('## Tech Recommendations');
    for (const r of roadmap.tech_recommendations) {
      lines.push(`### ${r.category}: ${r.recommended}`);
      lines.push('**Pros:**');
      for (const p of r.pros) lines.push(`- ✅ ${p}`);
      lines.push('**Cons:**');
      for (const c of r.cons) lines.push(`- ❌ ${c}`);
      if (r.alternatives.length > 0) {
        lines.push('**Alternatives:**');
        for (const a of r.alternatives) lines.push(`- **${a.name}** — ${a.reason}`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Generated by IdeaGen*');

  return lines.join('\n');
}

export function downloadMarkdown(roadmap: ProjectRoadmap): void {
  const md = roadmapToMarkdown(roadmap);
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${roadmap.title.replace(/[^a-zA-Z0-9]+/g, '-').toLowerCase()}-roadmap.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
